- name: Ansible command vs Shell module
  hosts: local
  connection: local
  tasks:
  - name: Command module test
    # ansible.builtin.command: cat /etc/passwd | grep root # Piping command won't work in command
    ansible.builtin.shell: cat /etc/passwd | grep root
    register: users_output

  - name: Print output
    ansible.builtin.debug:
      msg: "{{ users_output }}"

  - name: Command module test
    # ansible.builtin.command: cat /etc/passwd | grep root # Piping command won't work in command
    ansible.builtin.shell: ls -ltr > files.txt
    register: files_output

  - name: Print output of files
    ansible.builtin.debug:
      msg: "{{ files_output }}"